Fix compatibility with Maven 3.1.1
android-maven-plugin 3.7.0 is not compatible with Maven 3.1.1 and throws
ClassNotFoundException: org.sonatype.aether.RepositorySystem. Issue 395.
It sets minimal required Maven version to 3.1.1.